(defvar p01--attrib-list '((" *[：:] *" . " : ")
                           ("（" . "(")
                           ("）" . ")")
                           ("\\bint(" . "(int) (")
                           (" *\\+ *" . " + ")
                           (" *- *" . " - ")
                           (" *\\* *" . " * ")
                           (" */ *" . " / ")
                           ("\\b\\(\\([lL][Vv]\\)\\|\\(level\\)\\)\\b" . "LV")
                           ("物理吸收效果" . "\"phy_absorb\"")
                           ("法术吸收效果" . "\"mag_absorb\"")
                           ("物理攻击效果" . "\"phy_effect\"")
                           ("法术攻击效果" . "\"mag_effect\"")
                           ("速度效果" . "\"speed_effect\"")
                           ("道行效果" . "\"tao_effect\"")
                           ("气血效果" . "\"life_effect\"")
                           ("破防度" . "\"penetrate\"")
                           ("破防率" . "\"penetrate_rate\"")
                           ("抗所有异常". "\"all_resist_except \"")
                           ))

(defun p01//replace-all-attribs (str)
  "用p01--attrib-list中的键值对属性替换str中对应字符"
  (dolist (elt p01--attrib-list)
    (setq str
          (replace-regexp-in-string (car elt) (cdr elt) str 1)))
  str)

(defun p01/translate-attribs (begin end)
  (interactive "r")
  (insert
   (p01//replace-all-attribs (delete-and-extract-region begin end))))
